### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.Initiator#14]
# Description
Use DocFX to auto generate documentation.

# Tasks
- [x] Update build script (See VaraniumSharp one)
- [x] Update AppVeyor so bot can push documents back
- [x] Create gh-pages branch
- [x] Push in initial version of documents
