### ISSUE TITLE
Create Application Insight wrapper

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.Initiator#21]
# Description
Application Insights has an instanced library that needs to be passed into each class that uses it. Create a wrapper that holds it in a static class so that data can be easily sent to application insight.
The class should have an initialization method that lets the program set the details it needs and only once it has been initialized should it send data to Azure.
Also implement the ability to disable tracking should it be desired

# Tasks
- [x] Create ApplicationInsight helper class
- [ ] Initialization method needs to be seperate
- [ ] Add property that allows for disabling/enabling data gathering
- [ ] Create wrapper methods for most of the application insight client's methods
